# Site settings
title: Dinesh Krishna Natarajan
description: Personal Webpage
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dinesh-k-natarajan.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dinesh Krishna Natarajan
user_description: I am a Graduate Student of Computational Mechanics with a cross-domain experience in Machine Learning, Multidisciplinary Optimization and Software Development. I'm very passionate towards futuristic technologies at the intersection of Artificial Intelligence and Autonomous Driving. Everyday I'm working towards making the Science Fiction of our generation into the Reality of the next.
user_title: Graduate Student at Uni Stuttgart
email: dineshkrishna.natarajan@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
